version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - nextcloud-db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=QCorporation#3
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data

  app:
    image: nextcloud:apache
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html:z
    environment:
      - VIRTUAL_HOST=nextqloud.mooo.com
      - LETSENCRYPT_HOST=nextqloud.mooo.com
      - LETSENCRYPT_EMAIL=jumaga2015@gmail.com

      - MYSQL_HOST=db
      - REDIS_HOST=redis

      - TRUSTED_PROXIES=proxy
      - OVERWRITECLIURL=https://nextqloud.mooo.com
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextqloud.mooo.com  
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud-data:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - proxy-certs:/etc/nginx/certs:z,ro
      - proxy-vhost.d:/etc/nginx/vhost.d:z
      - proxy-html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - proxy-certs:/etc/nginx/certs:z
      - proxy-vhost.d:/etc/nginx/vhost.d:z
      - proxy-html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/var/run/docker.sock:z,ro
      - letsencrypt:/etc/acme.sh:z
    networks:
      - proxy-tier
    depends_on:
      - proxy

# self signed
#  omgwtfssl:
#    image: paulczar/omgwtfssl
#    restart: "no"
#    volumes:
#      - certs:/certs
#    environment:
#      - SSL_SUBJECT=servhostname.local
#      - CA_SUBJECT=my@example.com
#      - SSL_KEY=/certs/servhostname.local.key
#      - SSL_CSR=/certs/servhostname.local.csr
#      - SSL_CERT=/certs/servhostname.local.crt
#    networks:
#      - proxy-tier

  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    networks:
      - proxy-tier
    depends_on:
      - proxy
    cap_add:
     - MKNOD
    ports:
      - 127.0.0.1:9980:9980
    environment:
      # IMPORTANT: Note the backslashs before the dots here (and only here)!
      - domain=nextqloud.mooo.com
      - username=admin
      - password=QCorporation#3
      - VIRTUAL_HOST=officeqloud.mooo.com
      - LETSENCRYPT_HOST=officeqloud.mooo.com
      - VIRTUAL_NETWORK=proxy-tier
      - VIRTUAL_PORT=9980
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    #En nextcloud configuración office, poner este host <https://officeqloud.mooo.com>

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: always  
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      - 49100-49200:49100-49200/udp
   volumes:
      - coturn-data:/var/lib/coturn
   command: --log-file=stdout --min-port=49100 --max-port=49200 --fingerprint --stale-nonce --no-multicast-peers --use-auth-secret --static-auth-secret=26c10e36382f904ec6aa03eb33ebe0a0d09ef6b5bdc7ca080459e83e1a962699 --no-cli --no-tlsv1 --no-tlsv1_1 --realm=emvudotracks.duckdns.org --total-quota=100
   depends_on:
      - redis

  cloudflare-ddns:
    environment:
      - API_KEY=1O0DEillqBQ2LqT-9TBnVBCO5ZJmATC_bwZiEKs-
      - ZONE=qloudserver.es
      - SUBDOMAIN=mail
    image: oznu/cloudflare-ddns

volumes:
  nextcloud-db:
  nextcloud-data:
  proxy-certs:
  proxy-vhost.d:
  proxy-html:
  letsencrypt:
  redis-data:
    driver: local
  coturn-data:

networks:
  proxy-tier:
