services:

  db:
    image: mariadb:10.6
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - nextcloud-db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=QCorporation#3
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file: ./db/db.env  

  # crear este fichero en el sistema host con root.
  # echo "vm.overcommit_memory = 1" > /etc/sysctl.d/10-overcommit.conf
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    restart: always
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - openldap-certificates:/container/service/slapd/assets/certs
      - openldap-slapd-database:/var/lib/ldap
      - openldap-slapd-config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=QCorporation
      - LDAP_DOMAIN=qloudserver.es
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=qloud
      - LDAP_CONFIG_PASSWORD=config_pass
      #cn=admin,dc=qloudserver,dc=es
      - LDAP_BASE_DN=dc=qloudserver,dc=es
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=qloudserver.es.ca.crt
      - LDAP_REQUIRE_STARTTLS=TRUE
      - LDAP_TLS_VERIFY_CLIENT=never

      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=qloud

      #- LDAP_LOG_LEVEL=0
    networks:
      - proxy-tier
      - openldap
  
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "9080:80"
    volumes:
      - phpldapadmin-data:/var/www/phpldapadmin      
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

  lumqloud:
    image: wheelybird/ldap-user-manager:v1.11  
    container_name: lumqloud
    restart: always
    volumes:
      - openldap-certificates:/container/service/slapd/assets/certs:ro
    #Sin proxy descomentar
    #ports: 
    #    - 80:80
    #    - 443:443
    environment:
      - VIRTUAL_HOST=lumqloud.qloudserver.es
      - LETSENCRYPT_HOST=lumqloud.qloudserver.es
      - LETSENCRYPT_EMAIL=jumaga2015@gmail.com

      - NO_HTTPS=TRUE

      - SERVER_HOSTNAME=openldap.qloudserver.es
      - LDAP_URI=ldaps://openldap
      - LDAP_BASE_DN=dc=qloudserver,dc=es
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=qloudserver,dc=es
      - LDAP_ADMIN_BIND_PWD=qloud

      - LDAP_REQUIRE_STARTTLS=TRUE
      - LDAP_IGNORE_CERT_ERRORS=TRUE

      - EMAIL_DOMAIN=qloudserver.es
    depends_on:
      - openldap
    networks:
      - proxy-tier    
      - openldap

  mailserver:
    build:
      context: ./mailserver
      dockerfile: Dockerfile
    container_name: mailserver
    restart: always
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.qloudserver.es
    environment:
      # SSL_TYPE:         Uses the `letsencrypt` method to find mounted certificates.
      # VIRTUAL_HOST:     The FQDN that `nginx-proxy` will configure itself to handle for HTTP[S] connections.
      # LETSENCRYPT_HOST: The FQDN for a certificate that `acme-companion` will provision and renew.
      - SSL_TYPE=letsencrypt
      - VIRTUAL_HOST=mail.qloudserver.es
      - LETSENCRYPT_HOST=mail.qloudserver.es    

      # >>> Postfix LDAP Integration
      - LDAP_START_TLS=no
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=ldaps://openldap:636
      - LDAP_BIND_DN=cn=admin,dc=qloudserver,dc=es
      - LDAP_BIND_PW=qloud

      - LDAP_SEARCH_BASE=dc=qloudserver,dc=es
      - LDAP_QUERY_FILTER_DOMAIN=(|(mail=*@%s)(mailAlias=*@%s)(mailGroupMember=*@%s))
      - LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(mail=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetOrgPerson)(mailAlias=%s))
      - LDAP_QUERY_FILTER_GROUP=(&(objectClass=inetOrgPerson)(mailGroupMember=%s))
      - LDAP_QUERY_FILTER_SENDERS=(&(objectClass=inetOrgPerson)(|(mail=%s)(mailAlias=%s)(mailGroupMember=%s)))
      - SPOOF_PROTECTION=1
      # cmdtest: postmap -q qloudserver.es ldap:/etc/postfix/ldap-domains.cf
      # cmdtest: postmap -q admin-ldap@qloudserver.es ldap:/etc/postfix/ldap-users.cf
      # <<< Postfix LDAP Integration

      # >>> Dovecot LDAP Integration
      - DOVECOT_TLS=no
      - DOVECOT_TLS_REQCERT=never
      - DOVECOT_AUTH_BIND=no
      #- DOVECOT_AUTH_BIND_USERDN=cn=%u,ou=people,dc=qloudserver,dc=es

      - DOVECOT_USER_FILTER=(&(objectClass=inetOrgPerson)(userid=%n))
      - DOVECOT_PASS_FILTER=(&(objectClass=inetOrgPerson)(mail=%u))
      - DOVECOT_PASS_ATTRS=uid=user,userPassword=password
      - DOVECOT_USER_ATTRS==home=/var/mail/%{ldap:uid},=mail=maildir:~/Maildir,uidNumber=uid,gidNumber=gid
      # cmdtest: doveadm auth test admin-ldap@qloudserver.es qloudqloudqloud
      # cmdtest: doveadm auth lookup admin-ldap@qloudserver.es
      # cmdtest: doveadm auth login admin-ldap@qloudserver.es qloudqloudqloud
      # <<< Dovecot LDAP Integration

      # >>> SASL LDAP Authentication
      - SASLAUTHD_LDAP_START_TLS=no
      - ENABLE_SASLAUTHD=0
      - SASLAUTHD_LDAP_SERVER=openldap.qloudserver.es
      - SASLAUTHD_LDAP_PROTO=
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=qloudserver,dc=es
      - SASLAUTHD_LDAP_PASSWORD=qloud
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=qloudserver,dc=es
      - SASLAUTHD_LDAP_FILTER=(&(mail=%U@qloudserver.es)(objectClass=inetOrgPerson))
      - SASLAUTHD_MECHANISMS=ldap
      # <<< SASL LDAP Authentication

    env_file: ./mailserver/mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - dms-mail-data:/var/mail/
      - dms-mail-state:/var/mail-state/
      - dms-mail-logs:/var/log/mail/
      - dms-config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - proxy-certs:/etc/letsencrypt/live/:ro
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - proxy-tier


  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: always
    hostname: nextqloud.qloudserver.es
    volumes:
      - nextcloud-data:/var/www/html:z
    environment:
      - VIRTUAL_HOST=nextqloud.qloudserver.es
      - LETSENCRYPT_HOST=nextqloud.qloudserver.es
      - LETSENCRYPT_EMAIL=jumaga2015@gmail.com

      - MYSQL_HOST=db
      - REDIS_HOST=redis

      - TRUSTED_PROXIES=proxy
      - OVERWRITECLIURL=https://nextqloud.qloudserver.es
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextqloud.qloudserver.es  
    env_file: ./db/db.env
    depends_on:
      - db
      - redis
      - mailserver
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud-data:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      # you can remove port 81 after you have HTTPS setup to your Nginx Proxy Manager admin page
      - 81:81
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - proxy-certs:/etc/nginx/certs:z,ro
      - proxy-vhost.d:/etc/nginx/vhost.d:z
      - proxy-html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - proxy-certs:/etc/nginx/certs:z
      - proxy-vhost.d:/etc/nginx/vhost.d:z
      - proxy-html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/var/run/docker.sock:z,ro
      - letsencrypt:/etc/acme.sh:z
    networks:
      - proxy-tier
    depends_on:
      - proxy

# self signed
#  omgwtfssl:
#    image: paulczar/omgwtfssl
#    restart: "no"
#    volumes:
#      - certs:/certs
#    environment:
#      - SSL_SUBJECT=servhostname.local
#      - CA_SUBJECT=my@example.com
#      - SSL_KEY=/certs/servhostname.local.key
#      - SSL_CSR=/certs/servhostname.local.csr
#      - SSL_CERT=/certs/servhostname.local.crt
#    networks:
#      - proxy-tier

  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    networks:
      - proxy-tier
    depends_on:
      - proxy
    cap_add:
     - MKNOD
    ports:
      - 127.0.0.1:9980:9980
    environment:
      # IMPORTANT: Note the backslashs before the dots here (and only here)!
      - domain=nextqloud.qloudserver.es
      - username=admin
      - password=QCorporation#3
      - VIRTUAL_HOST=officeqloud.qloudserver.es
      - LETSENCRYPT_HOST=officeqloud.qloudserver.es
      - VIRTUAL_NETWORK=proxy-tier
      - VIRTUAL_PORT=9980
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    #En nextcloud configuración office, poner este host <https://officeqloud.qloudserver.es>

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: always  
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      - 49100-49200:49100-49200/udp
    volumes:
      - coturn-data:/var/lib/coturn
    command: --log-file=stdout --realm=nextqloud.qloudserver.es --min-port=49100 --max-port=49200 --fingerprint --stale-nonce --no-multicast-peers --use-auth-secret --static-auth-secret=26c10e36382f904ec6aa03eb33ebe0a0d09ef6b5bdc7ca080459e83e1a962699 --no-cli --no-tlsv1 --no-tlsv1_1 --total-quota=100
    depends_on:
      - redis

  cloudflare-ddns:
    container_name: cloudflare-ddns
    restart: always  
    environment:
      - API_KEY=1O0DEillqBQ2LqT-9TBnVBCO5ZJmATC_bwZiEKs-
      - ZONE=qloudserver.es
      - SUBDOMAIN=mail
    image: oznu/cloudflare-ddns

volumes:
  openldap-certificates:
  openldap-slapd-database:
  openldap-slapd-config:
  phpldapadmin-data:  
  dms-mail-data:
  dms-mail-state:
  dms-mail-logs:
  dms-config:
  nextcloud-db:
  nextcloud-data:
  proxy-certs:
  proxy-vhost.d:
  proxy-html:
  letsencrypt:
  redis-data:
    driver: local
  coturn-data:

networks:
  proxy-tier:
  openldap:
    driver: bridge